config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :commentable do
    resources :comments, except: [:index, :show]
  end

  concern :votable do
    patch :thumbs_up, on: :member
    patch :thumbs_down, on: :member
  end

  root to: 'questions#index'

  get 'search', to: 'search#search', as: 'search'
  get 'tags/:tag', to: 'search#search', as: 'tag'

  resource :profiles, only: [:edit, :update] do
    get :me, on: :collection
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, except: [:index, :show], concerns: [:commentable, :votable] do
      patch :approve, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/question.rb
class Question < ActiveRecord::Base
	include Votable

	belongs_to :user
	has_many :answers, dependent: :destroy, inverse_of: :question
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :attachments, as: :attachmentable, dependent: :destroy
	has_and_belongs_to_many :tags

	before_save :associate_tags

	attr_writer :tag_names

	validates :title, :body, presence: true

	accepts_nested_attributes_for :attachments, allow_destroy: true

	scope :latest, -> { where("created_at >= ?", Time.zone.now - 1.day) }

	def solution
		answers.find_by(approved: true)
	end

	def has_solution?
		solution ? true : false
	end

	def tag_names
		@tag_names || tags.pluck(:name).join(', ')
	end

	def self.tagged_with(name)
		Tag.find_by!(name: name).questions
	end

	private

	def associate_tags
		if @tag_names
			self.tags = @tag_names.split(',').map do |name|
				Tag.find_or_create_by(name: name.strip)
			end
		end
	end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
	authorize_resource

	def index
		@questions = Question.all
		respond_with @questions, each_serializer: SimpleQuestionSerializer
	end

	def show
		@question = Question.find(params[:id])
		respond_with @question, serializer: CompleteQuestionSerializer, root: :question
	end

	def create
		@question = current_resource_owner.questions.create(question_params)
		respond_with @question, serializer: CompleteQuestionSerializer, root: :question
	end

	private

	def question_params
		params.require(:question).permit(:title, :body)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	authorize_resource

	include VotableController
	
	before_action :authenticate_user!, except: [:index, :show]
	before_action :load_question, except: [:new, :index, :show, :create]

	def index
		@questions = Question.includes(:tags).order(created_at: :desc)
	end

	def show
		@question = Question.includes(:tags, :comments, :attachments, answers: [:comments, :attachments]).find(params[:id])
	end

	def new
		@question = Question.new

		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def edit
		respond_to do |format|
			format.html { redirect_to @question }
			format.js
		end
	end

	def create
		@question = current_user.questions.build(question_params)

		respond_to do |format|
			if @question.save
				flash[:notice] = 'Your question was successfully created.'
				format.js do
					@questions = Question.order(created_at: :desc)
					PrivatePub.publish_to '/questions', question: Question.order(created_at: :desc).to_json
				end
			else
				format.js { render :new }
			end
		end
	end

	def update
		respond_to do |format|
			if @question.update(question_params)
				format.js
			else
				format.js { render :edit }
			end
		end
	end

	def destroy
		@question.destroy
		redirect_to questions_path
	end

	def verificate_authorship
		@record = @question
		super
	end

	private

	def resource
		@question
	end

	def load_question
		@question = Question.find(params[:id])
	end

	def question_params
		params.require(:question).permit(:title, :body, :tag_names, attachments_attributes: [:id, :file, :_destroy, :file_cache])
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
	def styling(votable)
		return { up: '', down: '' } unless votable.already_voted_by?(current_user)
		styling = votable.voted_with_by(current_user) ? { up: 'text-success', down: 'text-muted' } : { up: 'text-muted', down: 'text-danger' }
	end
end

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
	= render 'answers/answer', answer: answer

app/views/questions/_form.html.slim
= simple_nested_form_for @question, remote: true, html: { role: 'form' } do |f|
	= f.input :title, autofocus: true, input_html: { data: { role: 'somerole' } }
	= f.input :body, input_html: { rows: 4 }
	= f.input :tag_names, label: 'Tags', input_html: { data: { role: 'tagsinput' } }
	.form-attachments class='col-sm-12 text-center'
		- unless @question.attachments.empty? 
		  ul.list-inline
			  = render @question.attachments
	br
	= f.simple_fields_for :attachments, @question.attachments.build do |a|
		= a.input :file, wrapper_html: { class: 'hidden' }
	= f.link_to_add 'Add new file', :attachments, class: 'btn btn-default btn-sm'
	.text-center
		= f.button :submit, "#{ @question.new_record? ? 'Create question' : 'Update question' }", class: 'btn btn-success'

app/views/questions/_question.html.slim
.row
	.col-sm-2 class='question-ratings'
		.col-sm-6 class='given_votes text-center'
			span.h3 = question.rating_in_percent
			br
			p rating
		.col-sm-6 class='given_answers text-center'	
			span.h3 = question.answers_count 
			br
			p = 'answer'.pluralize(question.answers_count)
		
	.col-sm-10
		= link_to question.title, question, class: 'h3'
		- unless question.tags.empty?
			.tags
				= render question.tags
hr

app/views/questions/_questions.html.slim
- @questions.each do |question|
	= render 'questions/question', question: question

app/views/questions/_search_form.html.slim
.row
  .search class='col-sm-8 col-sm-offset-2'
    = form_tag '/search', method: :get, remote: true do
      .input-group
        = text_field_tag :q, nil, class: 'form-control', placeholder: 'our magnificent...'
        span class="input-group-btn"
          button#search-options class="btn btn-default" type="button"
            i.fa class='fa-wrench'
      .filters class='hidden'
        = label_tag :search_questions, class: 'checkbox-inline'
          = check_box_tag :search_questions, 1, true
          | questions
        = label_tag :search_answers, class: 'checkbox-inline'
          = check_box_tag :search_answers, 1, true
          | answers
        = label_tag :search_comments, class: 'checkbox-inline'
          = check_box_tag :search_comments, 1, true
          | comments
      = submit_tag 'Search', class: 'btn btn-info btn-lg custom-width', id: 'search'

app/views/questions/_subscriptions.html.slim
= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"

- @question.answers.each do |answer|
	= subscribe_to "/answers/#{answer.id}/comments"

app/views/questions/create.js.erb
window.location='<%= j "#{question_path(@question)}" %>'

<% publish_to "/questions" do %>
	$('#questionsTabs #new').html('<%= j render "questions/questions" %>')
<% end %>

app/views/questions/edit.html.slim
.row
	.col-sm-8 class='col-sm-offset-2'
		h1 Edit question
		= render 'form'
		= link_to 'Show', @question
		| &nbsp; 
		= link_to 'Back', questions_path

app/views/questions/edit.js.erb
$('.modal-title').html('Edit question');
$('.modal-body').html('<%= j render 'form' %>');
$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();

app/views/questions/index.html.slim
.row
  .col-sm-12 class='starter-template text-center'
    h1 Solve Simple your problems
    p.lead
      | This is a short list of problems which humanity tries to solve in their everyday life.
      br
      | Help them and get some karma points, because the last thing you would like to do is joking bad with karma.
      br
      | You can try to look for an answer by
    
    = render 'search_form'
    - if can?(:create, Question)
      p.lead
        | or you can ask community for help with
      .ask
        = link_to 'Ask question', new_question_path, remote: true, class: 'btn btn-primary btn-lg custom-width', id: 'ask-question',
          data: { toggle: 'modal', target: '#formModal'}
    hr

.row
  #questionsTabs class='col-sm-12' role='tabpanel'
    ul class='nav nav-tabs' role='tablist'
      li role='presentation' class='active'
        a href='#new' aria-controls='new' role='tab' data-toggle='tab' New
      li role='presentation'
        a href='#hot' aria-controls='hot' role='tab' data-toggle='tab' Hot
    .tab-content
      .tab-pane class='active' role='tabpanel' id='new'
        = render 'questions/questions'
      .tab-pane role='tabpanel' id='hot'
        | Hot

= subscribe_to '/questions'

app/views/questions/new.html.slim
.row
	.col-sm-8 class='col-sm-offset-2'
		h1 New question
		= render 'form'
		= link_to 'Back', questions_path

app/views/questions/new.js.erb
$('.modal-title').html('New question');
$('.modal-body').html('<%= j render 'form' %>');
$("input[data-role=tagsinput], select[multiple][data-role=tagsinput]").tagsinput();

app/views/questions/show.html.slim
.row
  .col-sm-10 class='col-sm-offset-1'
    article#question class='row' data-commentable="question-#{@question.id}"
      .h1
        = link_to @question.title, @question
      hr
      
      = render 'votes/vote', votable: @question

      .col-sm-10
        p.lead
          = @question.body
        - unless @question.tags.empty?
          #tags class='col-sm-6'
            = render @question.tags
        - unless @question.attachments.empty? 
          .attachments class='col-sm-6 text-right'
            ul.list-inline
              = render @question.attachments
      .col-sm-10 class='col-sm-offset-2 controls'
        .col-sm-6
          - if can?(:create, Comment)
            = link_to 'Leave comment', new_question_comment_path(@question), remote: true,
              data: { toggle: 'modal', target: '#formModal' }
        .text-right class='col-sm-6'
          - if can?(:update, @question, user: current_user)
            .question-controls
              = link_to 'Back', questions_path
              |&nbsp;
              = link_to 'Edit', edit_question_path(@question), remote: true,
                data: { toggle: 'modal', target: '#formModal' }
              |&nbsp;
              = link_to 'Delete', @question, method: :delete, data: { confirm: 'Are you sure?' }
    - unless @question.comments.empty?
      .col-sm-12
        .comments id="question-#{@question.id}-comments" class='well well-sm'
          = render 'comments/comments', commentable: @question
    - if can?(:create, Answer)
      .text-center
        = link_to 'Add answer', new_question_answer_path(@question), remote: true, class: 'btn btn-primary btn-lg',
          data: { toggle: 'modal', target: '#formModal' }
    .row
      hr
    .row
      h2#answers-number = pluralize(@question.answers.size, 'answer')
    #answers 
      = render 'questions/answers'

= render 'questions/subscriptions'

app/views/questions/update.js.erb
$('#formModal').modal('toggle');

if( $('.alert-info').length ){
	$('.alert-info').html('Your question was successfully updated.');
} else {
	$('#main').prepend('<div class="alert alert-info">Your question was successfully updated.</div>');
}

$('#question .h1 a').html('<%= j "#{@question.title}" %>');
$('#question p.lead').html('<%= j "#{@question.body}" %>');
$('#tags').html('<%= j render @question.tags %>')