config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :commentable do
    resources :comments, except: [:index, :show]
  end

  concern :votable do
    patch :thumbs_up, on: :member
    patch :thumbs_down, on: :member
  end

  root to: 'questions#index'

  get 'search', to: 'search#search', as: 'search'
  get 'tags/:tag', to: 'search#search', as: 'tag'

  resource :profiles, only: [:edit, :update] do
    get :me, on: :collection
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, except: [:index, :show], concerns: [:commentable, :votable] do
      patch :approve, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, polymorphic: true

	validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_commentable, only: [:new, :create]
	before_action :load_comment, only: [:edit, :update, :destroy]

	authorize_resource

	def new
		@comment = @commentable.comments.build

		respond_to do |format|
			format.html { redirect_to @commentable }
			format.js
		end
	end

	def create
		@comment = @commentable.comments.build(comment_params.merge(user: current_user))
		
		respond_to do |format|
			if @comment.save
				format.js
			else
				format.js { render :new }
			end
		end
	end

	def edit
		respond_to do |format|
			format.html { redirect_to @comment.commentable }
			format.js
		end
	end

	def update
		respond_to do |format|
			if @comment.update(comment_params)
				format.js
			else
				format.js { render :edit }
			end
		end
	end

	def destroy
		@comment.destroy
		@record = @comment.commentable

		@record = @record.question if @record.is_a? Answer
			
		redirect_to @record
	end

	private

	def load_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:body)
	end

	def set_commentable
		resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.slim
.comments-section  
  - commentable.comments.each do |comment|
		.comment class='col-sm-12'
			.comment-body class='col-sm-11'
				= comment.body
			- if can?(:update, comment, user: current_user)
				.comment-controls class='col-sm-1 text-center'
					= link_to edit_comment_path(comment), remote: true, data: { toggle: 'modal', target: '#formModal' } do
						i.fa class='fa-paint-brush'
					|&nbsp;
					= link_to comment, method: :delete do
						i.fa class='fa-trash'
p.text-center
	= link_to 'Hide comments', '#'

app/views/comments/_form.html.slim
= simple_form_for [@commentable, @comment], remote: true, html: { role: 'form' } do |f|
	= f.input :body, input_html: { rows: 4 }, autofocus: true
	.text-center
		= f.button :submit, "#{ @comment.new_record? ? 'Create comment' : 'Update comment' }", class: 'btn btn-success'

app/views/comments/create.js.erb
$('#formModal').modal('toggle');

if( $('.alert-info').length ){
	$('.alert-info').html('Your comment was successfully created.');
} else {
	$('#main').prepend('<div class="alert alert-info">Your comment was successfully created.</div>');
}

<% publish_to "/#{@comment.commentable_type.downcase.pluralize}/#{@commentable.id}/comments" do %>
	var selector = '<%= "#{@comment.commentable_type.downcase}-#{@commentable.id}-comments" %>';

	if( $('#' + selector).length === 0 ){
	$("[data-commentable='<%= j "#{@comment.commentable_type.downcase}-#{@comment.commentable.id}" %>']").
				append('<div class="col-sm-12"><div id="' + selector + '" class="comments well well-sm"></div></div>');
  } 

	$('#' + selector).html('<%= j render "comments/comments", commentable: @comment.commentable %>');
<% end %>

app/views/comments/edit.js.erb
$('.modal-title').html('Edit comment');
$('.modal-body').html('<%= j render 'form' %>');

app/views/comments/new.js.erb
$('.modal-title').html('New comment');
$('.modal-body').html('<%= j render 'form' %>');

app/views/comments/update.js.erb
$('#formModal').modal('toggle');

if( $('.alert-info').length ){
	$('.alert-info').html('Your comment was successfully updated.');
} else {
	$('#main').prepend('<div class="alert alert-info">Your comment was successfully updated.</div>');
}

$('#<%= j "#{@comment.commentable_type.downcase}-#{@comment.commentable.id}-comments" %>').html('<%= j render "comments/comments", commentable: @comment.commentable %>');