config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  concern :commentable do
    resources :comments, except: [:index, :show]
  end

  concern :votable do
    patch :thumbs_up, on: :member
    patch :thumbs_down, on: :member
  end

  root to: 'questions#index'

  get 'search', to: 'search#search', as: 'search'
  get 'tags/:tag', to: 'search#search', as: 'tag'

  resource :profiles, only: [:edit, :update] do
    get :me, on: :collection
  end

  resources :questions, concerns: [:commentable, :votable], shallow: true do
    resources :answers, except: [:index, :show], concerns: [:commentable, :votable] do
      patch :approve, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question, inverse_of: :answers, counter_cache: true
	has_many :comments, as: :commentable, dependent: :destroy
	has_many :attachments, as: :attachmentable, dependent: :destroy

	include Votable

	validates :body, presence: true

	accepts_nested_attributes_for :attachments

  default_scope { order("approved DESC, created_at") }

	def approve
		question = self.question

		if question.has_solution? && (question.solution != self)
			question.solution.update(approved: false)
      self.update(approved: true)
		elsif !question.has_solution?
			self.update(approved: true)
		end

		self
	end

  def is_a_solution?
    self.approved
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	authorize_resource

	include VotableController

	before_action :authenticate_user!
	before_action :get_question, only: [:new, :create]
	before_action :load_answer, except: [:new, :create]

	def new
		@answer = @question.answers.build

		respond_to do |format|
			format.html { redirect_to @question }
			format.js
		end
	end

	def edit
		respond_to do |format|
			format.html { redirect_to @answer.question }
			format.js
		end
	end

	def create
		@answer = @question.answers.build(answer_params.merge(user: current_user))

		respond_to do |format|
			if @answer.save
				format.js
			else
				format.js { render :new }
			end
		end
	end

	def update
		@question = @answer.question

		respond_to do |format|
			if @answer.update(answer_params)
				format.js
			else
				@question = nil
				format.js { render :edit }
			end
		end
	end

	def destroy
		@answer.destroy
		redirect_to @answer.question
	end

	def approve
		@question = @answer.question
		@answer.approve
	end

	private

	def resource
		@answer || load_answer
	end

	def get_question
		@question = Question.find(params[:question_id])
	end

	def load_answer
		@answer = Answer.find(params[:id])
	end

	def answer_params
		params.require(:answer).permit(:body, attachments_attributes: [:file])
	end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
	authorize_resource

	before_action :load_question, only: [:index, :show, :create]

	def index
		@answers = @question.answers
		respond_with @answers, each_serializer: SimpleAnswerSerializer
	end

	def show
		@answer = @question.answers.find(params[:id])
		respond_with @answer, serializer: CompleteAnswerSerializer, root: :answer
	end

	def create
		@answer = @question.answers.create(answer_params.merge(user: current_resource_owner))
		respond_with @answer, serializer: CompleteAnswerSerializer, root: :answer
	end

	private 

	def load_question
		@question = Question.find(params[:question_id])
	end

	def answer_params
		params.require(:answer).permit(:body)
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer.row class=('bg-success approved' if answer.is_a_solution?) data-commentable="answer-#{answer.id}"
	= render 'votes/vote', votable: answer

	.col-sm-8
		p = answer.body
		- unless answer.attachments.empty? 
			.attachments class='col-sm-6 col-sm-offset-6 text-right'
				ul.list-inline
				  = render answer.attachments
	- if can?(:approve, answer)
		.approving class='col-sm-2 text-center'
			= link_to approve_answer_path(answer), method: :patch, remote: true do
				i.fa class='fa-check fa-2x'
	.col-sm-10 class='col-sm-offset-2 controls'
		.col-sm-6
			- if can?(:create, Comment)
				= link_to 'Leave comment', new_answer_comment_path(answer), remote: true,
					data: { toggle: 'modal', target: '#formModal' }
		.text-right	class='col-sm-6'
			- if can?(:update, answer, user: current_user)
				.answern-controls
					= link_to 'Edit', edit_answer_path(answer), remote: true,
						data: { toggle: 'modal', target: '#formModal' }
					|&nbsp;
					= link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' }
	- unless answer.comments.empty?
		.col-sm-12
			.comments id="answer-#{answer.id}-comments" class='well well-sm'
				= render 'comments/comments', commentable: answer
		

app/views/answers/_form.html.slim
= simple_nested_form_for [@question, @answer], remote: true, html: { role: 'form' } do |f|
	= f.input :body, input_html: { rows: 4 }, autofocus: true
	.form-attachments class='col-sm-12 text-center'
	  - unless @answer.attachments.empty?
	    ul.list-inline 
			  = render @answer.attachments
	= f.simple_fields_for :attachments, @answer.attachments.build do |a|
		= a.input :file, wrapper_html: { class: 'hidden' }
	= f.link_to_add 'Add new file', :attachments, class: 'btn btn-default btn-sm'
	.text-center
		= f.button :submit, "#{ @answer.new_record? ? 'Create answer' : 'Update answer' }", class: 'btn btn-success'

app/views/answers/approve.js.erb
if( $('.alert-info').length ){
	$('.alert-info').html('You have successfully approved an answer to your question.');
} else {
	$('#main').prepend('<div class="alert alert-info">You have successfully approved an answer to your question.</div>');
}

$('#answers').html('<%= j render "questions/answers" %>');

app/views/answers/create.js.erb
$('#formModal').modal('toggle');

if( $('.alert-info').length ){
	$('.alert-info').html('Your answer was successfully created.');
} else {
	$('#main').prepend('<div class="alert alert-info">Your answer was successfully created.</div>');
}

<% publish_to "/questions/#{@question.id}/answers" do %>
	$('#answers-number').html('<%= j "#{pluralize(@question.answers.size + 1, 'answer')}" %>')
	$('#answers').html('<%= j render "questions/answers" %>');
<% end %>

app/views/answers/edit.js.erb
$('.modal-title').html('Edit answer');
$('.modal-body').html('<%= j render 'form' %>');

app/views/answers/new.js.erb
$('.modal-title').html('New answer');
$('.modal-body').html('<%= j render 'form' %>');

app/views/answers/update.js.erb
$('#formModal').modal('toggle');

if( $('.alert-info').length ){
	$('.alert-info').html('Your answer was successfully updated.');
} else {
	$('#main').prepend('<div class="alert alert-info">Your answer was successfully updated.</div>');
}

$('#answers').html('<%= j render "questions/answers" %>');